### ISSUE TITLE
Unable to execute becuase of missing module 'babel-runtime/regenerator'

### ISSUE THREAD

**Issue by murthypattisapu** [standard-library/wire-o#16]
This is the repsonse from the API
{
    "errorMessage": "Cannot find module 'babel-runtime/regenerator'",
    "errorType": "Error",
    "stackTrace": [
        "Module.require (module.js:497:17)",
        "require (internal/module.js:20:19)",
        "Object.<anonymous> (/var/task/dist/app.js:3:20)",
        "Module._compile (module.js:570:32)",
        "Object.Module._extensions..js (module.js:579:10)",
        "Module.load (module.js:487:32)",
        "tryModuleLoad (module.js:446:12)",
        "Function.Module._load (module.js:438:3)"
    ]
}
I am completley new to babel and npm, so tried some links i found in web by changing babel versions but it did not solve the issue.

Cloud watch logs  : 
Unable to import module 'dist/app': Error
at Function.Module._load (module.js:417:25)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (/var/task/dist/app.js:3:20)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)

Is this related to new babel version?

My pacagke.json diff
   },
   "dependencies": {
     "aws-sdk": "^2.6.9",
+    "babel": "^6.23.0",
     "bluebird": "^3.4.6",
     "mkdirp": "^0.5.1",
     "node-uuid": "^1.4.7",
@@ -19,14 +20,17 @@
   },
   "devDependencies": {
     "aws-lambda-mock-context": "^3.0.0",
-    "babel-cli": "^6.18.0",
+    "babel-cli": "^6.26.0",
     "babel-eslint": "^7.0.0",
     "babel-plugin-transform-flow-strip-types": "^6.18.0",
+    "babel-plugin-transform-regenerator": "^6.26.0",
+    "babel-plugin-transform-runtime": "^6.23.0",
     "babel-plugin-transform-runtime ": "^6.23.0",
     "babel-polyfill": "^6.16.0",
-    "babel-preset-es2015": "^6.18.0",
-    "babel-preset-stage-2": "^6.18.0",
+    "babel-preset-es2015": "^6.24.1",
+    "babel-preset-stage-2": "^6.24.1",
     "babel-register": "^6.18.0",
+    "babel-runtime": "^6.26.0",
     "chai": "^3.5.0",
     "eslint": "^3.8.1",
     "eslint-plugin-flowtype": "^2.25.0",

**Comment by murthypattisapu** [comment]
Moving "babel-plugin-transform-regenerator": "^6.26.0",
"babel-plugin-transform-runtime": "^6.23.0", to dependencies instead of devDep solved the issue for me.

**Comment by rjimenezg** [comment]
Could you run the repo? I got it on my lambda but keeps giving me "null" as response.

**Comment by murthypattisapu** [comment]
I did not understand the comment, but after moving the dependecy. I had an issue with file permission on bin/pdftk, as i was deploying it from windows and the execute permission was missing. I had to deploy from Linux to make it work. I was also getting "null" response because of that. Check cloudwatch logs as it could be another issue.

**Comment by rjimenezg** [comment]
Exactly the same problem I am having. Thanks a lot! I will deploy from macOS and try, if not I will use linux. Thanks a lot!

**Comment by jackjennings** [comment]
All of the development for this was done on macOS, and I don’t have any experience developing for Windows, sorry.

I’m also not sure why the dependencies would need to be updated, but development on this has stopped for awhile and they may be out of date for the most recent node runtime available on Lambda.
