### ISSUE TITLE
Its not clear to me how to create the wire-o.yml

### ISSUE THREAD

**Issue by papagala** [standard-library/wire-o#17]
Unable to follow the steps after creating the wire-o.yml file. Not clear on how to create it plus what to do next.

**Comment by jackjennings** [comment]
What happens when you run `npm run deploy`?

**Comment by luis-17** [comment]
I get this error when processing CloudFormation: An error occurred: ServerlessDeploymentBucket - API: s3: CreateBucket Access Denied.

I understand that it tells me that I don't have permissions to create a bucket, but why would cloudformation have to create a bucket if I already configured one that is already created?
Help me pls

**Comment by jackjennings** [comment]
@luis-17 this application hasn't been maintained for several years and we can't offer support in deploying it.
